### PR TITLE
Kstemmer

### PR DESCRIPTION
**Pull request by fordmadox**
Adds the Krovetz Stemmer back, which we've had in production to handle simple stemming.  This works great, aside from two issues:

1.  It can occasionally break the typeahead search in the staff interface, since you need to remember to search for "volume" instead of "volumes", since as soon as you type in a trailing 's', you do not get any results.
2.  For some reason I don't understand, Solr's KStemmer does *not* stem "dogs" to "dog".  However, being able to search for either term and get the same results was one of our original search requirements.  To fix that issue, we've had "dog, dogs" in our synonyms.txt file in production, which this pull request adds back.  But we really need to add some other synonyms.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by fordmadox** [comment]
And proof that the Kstemmer doesn't stem "dogs", since I wouldn't believe it either
Screen Shot 2020-06-04 at 9 25 39 PM

**Comment by fordmadox** [comment]
Of course, adding a stemmer does impact the custom filter, since we would wind up with duplicate terms.  E.g. Coyle's war --> coyle's coyle coyle war.  

So, I'm going to change the order to put the custom filter last.  That should do it, I think.

**Comment by marktriggs** [comment]
it stems "cats" OK so this is clearly a conspiracy...

**Comment by fordmadox** [comment]
My hope was that it was a bit of an Easter egg / joke, expressing favoritism for 'shaggy dogs', due to the the untrimmed 's'.  

Still not sure the reason, but the inclusion of 'dogs' in the dictionary that the Krovetz Stemmer uses is intentional.  I even checked http://lexicalresearch.com/software.html to be certain.

**Comment by marktriggs** [comment]
Yeah, I went looking for other examples too :)  "eyes" was another

**Comment by fordmadox** [comment]
Sounds like another line to add to synonyms.txt :) 

Interestingly, I was able to get a definitive answer on the matter.  Those terms are not stemmed due to their appearance in the _Longman Dictionary of Contemporary English_.  All that could change in the near future, though, since the stemmer will be undergoing a revision, with a new release expected next year.

**Comment by fordmadox** [comment]
This is now part of the yale-development branch, so closing this out.  Still need to find out when the revised version of the Krovetz stemmer is released / incorporated into Solr.

**Pull request closed without merging**
