### PR TITLE
Ar 1329

### PR DESCRIPTION
**Pull request by cfitz**
@quoideneuf  what do you think?

### CODE REVIEW

**Comment by cfitz** [comment]
oops!

**Comment by marktriggs** [comment]
I think the traditional response to a PR with 250+ commits is "Looks good to me!" :)

**Comment by cfitz** [comment]
what the worst thing that could happen?

**Comment by quoideneuf** [comment]
Would hudmol be offended if we asked Github to unfork us? I'm getting tired of GH always then telling me how big my PR is.

**Comment by marktriggs** [comment]
I'm not hudmol, but also not offended.  Given that the hudmol repo is always a long way behind master it's unlikely to help anyone much...

**Comment by jambun** [comment]
I asked hudmol. She seemed nonplussed.

**Comment by cfitz** [comment]
I'm an American, so I'm actually not sure what "nonplussed" means. Does it have something to do with cricket?

**Pull request closed without merging**
