### PR TITLE
iconography reset

### PR DESCRIPTION
**Pull request by fordmadox**
Probably a better way to handle this, but since we changed a few of the icons, and since we have a couple of custom ones (e.g. yc-collection, which is actually from FA 5, but ASpace is still using FA 4), we've updated this file in our production system.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by fordmadox** [comment]
Screen Shot 2020-06-04 at 1 02 36 PM
 
Example of the collection icon, which replaces the 'box' in this case.

**Comment by payten** [comment]
Hi @fordmadox, we can apply this override via a plugin if that suits you?  Would  `yale_pui_customizations` or `yale_pui_css` be a good spot for this? We can submit a PR.

**Comment by fordmadox** [comment]
Yep, that would be great, thanks!

**Comment by payten** [comment]
@fordmadox awesome :)

This a code change, so might be more suited to `yale_pui_customizations`?  Has that been ported to the latest version?  I'm getting some errors from the template overrides.  Alternatively, I'm happy to port the changes to `yale_pui_css` and you can move them to wherever suits.

**Comment by payten** [comment]
Hi @fordmadox , `yale_pui_cusomizations` makes most sense looking at the contents of that plugin.  PR here: https://github.com/YaleArchivesSpace/yale_pui_customizations/pull/2.

**Comment by fordmadox** [comment]
Looks good with my local tests, so I'm closing this one out.  Thanks!

**Pull request closed without merging**
