### PR TITLE
javascript updates

### PR DESCRIPTION
**Pull request by fordmadox**
## Description

I am sure that there is a better way to do this, but our goal was to switch from the single chevron icon to the plus and minus icons.  This is what we've had in production for a while now, but submitting as a pull request so that we won't lose this change during this upgrade process (and the next, etc.).  That said, if there's a better way to make this change, we would be happy to implement it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by payten** [comment]
Hi @fordmadox, it looks like we can move this customisation into a plugi by applying the same overrides with pure CSS. Would that suit you? Was thinking the `aspace_yale_pui` or `yale_pui_css` plugin would be a good spot?

**Comment by fordmadox** [comment]
Either is fine, but if it's pure CSS in this case, we also have a monolithic CSS plugin here :  https://github.com/YaleArchivesSpace/yale_pui_css/tree/test.  I'm sure there's a better way to manage that, as well, but that's where we started with our initial rollout.

**Comment by payten** [comment]
Thanks @fordmadox, I've added a PR here against the `test` branch: https://github.com/YaleArchivesSpace/yale_pui_css/pull/4

**Comment by fordmadox** [comment]
Works great, so I'll go ahead close the pull request.

**Pull request closed without merging**
