### PR TITLE
update to filter out series that do not have a Resource record parent

### PR DESCRIPTION
**Pull request by fordmadox**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by payten** [comment]
Hi @fordmadox, we could apply this customization via a plugin if that works for you?

**Comment by fordmadox** [comment]
Sounds good, thanks!

**Comment by payten** [comment]
PR for `yale_pui_customizations` here: https://github.com/YaleArchivesSpace/yale_pui_customizations/pull/2

**Comment by fordmadox** [comment]
Local tests for the plugin fix look good, so I'm going to close out this pull request.

**Pull request closed without merging**
